version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/nextjs-base"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "roCal93"
    assignees:
      - "roCal93"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/strapi-base"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "roCal93"
    assignees:
      - "roCal93"
    commit-message:
      prefix: "deps"
      include: "scope"